language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - "pip setup.py install"
  - "pip install codecov"
  - "pip install pytest-cov"

script:
  - py.test --cov-report=xml --cov=pyfinmod tests/

after_success:
- bash <(curl -s https://codecov.io/bash)